package com.ejemplo.vaadin.admusuarios;

import com.ejemplo.vaadin.entidades.Usuario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Validator;
import com.vaadin.data.validator.EmailValidator;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Form;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class UsuarioForm extends Form {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

//	@AutoGenerated
//	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private Button btReset;

	@AutoGenerated
	private Button btGuardar;

	@AutoGenerated
	private TextField txtClave;

	@AutoGenerated
	private TextField txtEmail;

	@AutoGenerated
	private TextField txtApellidos;

	@AutoGenerated
	private TextField txtNombre;

	@AutoGenerated
	private Label label_1;

	private static final long serialVersionUID = 169403674041257105L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UsuarioForm() {
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Un Titulillo");
		//mainLayout.addComponent(label_1, "top:40.0px;left:60.0px;");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("-1px");
		txtNombre.setHeight("-1px");
		txtNombre.setRequired(true);
		txtNombre.setRequiredError("Requerido! LOSER!!!");
		//mainLayout.addComponent(txtNombre, "top:120.0px;left:60.0px;");
		
		// txtApellidos
		txtApellidos = new TextField();
		txtApellidos.setCaption("Apellidos");
		txtApellidos.setImmediate(false);
		txtApellidos.setWidth("280px");
		txtApellidos.setHeight("-1px");
		txtApellidos.setRequired(true);
		txtApellidos.setRequiredError("Requerido! LOSER!!!");
		//mainLayout.addComponent(txtApellidos, "top:120.0px;left:220.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("Email");
		txtEmail.setImmediate(false);
		txtEmail.setWidth("260px");
		txtEmail.setHeight("-1px");
		txtEmail.setRequired(true);
		txtEmail.addValidator(new EmailValidator("Un Mail! LOSER!!!!"));
		txtEmail.setRequiredError("Requerido! LOSER!!!");
		//mainLayout.addComponent(txtEmail, "top:180.0px;left:60.0px;");
		
		// txtClave
		txtClave = new TextField();
		txtClave.setCaption("Clave");
		txtClave.setImmediate(false);
		txtClave.setWidth("157px");
		txtClave.setHeight("-1px");
		txtClave.setRequired(true);
		txtClave.setRequiredError("Requerido! LOSER!!!");
		//mainLayout.addComponent(txtClave, "top:180.0px;left:343.0px;");
		
		// btGuardar
		btGuardar = new Button();
		btGuardar.setCaption("Guardar");
		btGuardar.setImmediate(false);
		btGuardar.setWidth("-1px");
		btGuardar.setHeight("-1px");
		//mainLayout.addComponent(btGuardar, "top:254.0px;left:60.0px;");
		
		// btReset
		btReset = new Button();
		btReset.setCaption("Reset");
		btReset.setImmediate(false);
		btReset.setWidth("-1px");
		btReset.setHeight("-1px");
		//mainLayout.addComponent(btReset, "top:254.0px;left:440.0px;");
		
		addField("txtNombre", txtNombre);
		addField("txtApellidos", txtApellidos);
		addField("txtEmail", txtEmail);
		addField("txtClave", txtClave);
		addField("btGuardar", btGuardar);
		addField("btReset", btReset);
		
		//return mainLayout;
	}
	
	
	
	public Button getBtReset() {
		return btReset;
	}



	public void setBtReset(Button btReset) {
		this.btReset = btReset;
	}



	public Button getBtGuardar() {
		return btGuardar;
	}



	public void setBtGuardar(Button btGuardar) {
		this.btGuardar = btGuardar;
	}



	public TextField getTxtClave() {
		return txtClave;
	}



	public void setTxtClave(TextField txtClave) {
		this.txtClave = txtClave;
	}



	public TextField getTxtEmail() {
		return txtEmail;
	}



	public void setTxtEmail(TextField txtEmail) {
		this.txtEmail = txtEmail;
	}



	public TextField getTxtApellidos() {
		return txtApellidos;
	}



	public void setTxtApellidos(TextField txtApellidos) {
		this.txtApellidos = txtApellidos;
	}



	public TextField getTxtNombre() {
		return txtNombre;
	}



	public void setTxtNombre(TextField txtNombre) {
		this.txtNombre = txtNombre;
	}



	public Label getLabel_1() {
		return label_1;
	}



	public void setLabel_1(Label label_1) {
		this.label_1 = label_1;
	}



	public void entidadFormulario(Usuario usuario){
		
		txtNombre.setValue(usuario.getNombres());
		txtApellidos.setValue(usuario.getApellidos());
		txtEmail.setValue(usuario.getCorreo());
		txtClave.setValue(usuario.getClave());
		
	}
	
	public Usuario formularioEntidad(){
		
		Usuario usuario = new Usuario();
		usuario.setNombres(txtNombre.getValue().toString());
		usuario.setApellidos(txtApellidos.getValue().toString());
		usuario.setCorreo(txtEmail.getValue().toString());
		usuario.setClave(txtClave.getValue().toString());
		
		return usuario;
	}
	

}
